# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'treineticApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for treineticApp

  target 'treineticAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'treineticAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'UICheckbox.Swift'

end
